export const products = [
  {
    _id: '626b313513a1dd17403748ec',
    index: 0,
    guid: '042a0122-1575-47a9-a3ed-6ef9ce30c59c',
    isActive: false,
    price_formated: '$1,465.51',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'green',
    name: 'Carla Henson',
    gender: 'female',
    company: 'CEDWARD',
    email: 'carlahenson@cedward.com',
    phone: '+1 (815) 567-2666',
    address: '936 Bassett Avenue, Dubois, Delaware, 6261',
    about:
      'Ea aliqua non eiusmod minim incididunt consectetur aute. Ut cillum nostrud laborum consequat ad ad ex eu ullamco laboris voluptate do velit in. Ex irure ex labore qui incididunt exercitation pariatur adipisicing nostrud. Proident nostrud id excepteur ut ad voluptate.\r\n',
    registered: '2021-08-05T01:38:06 +03:00',
    latitude: 24.143673,
    longitude: 109.110955,
    tags: [
      'aliquip',
      'adipisicing',
      'laborum',
      'nulla',
      'anim',
      'proident',
      'aliquip',
    ],
    friends: [
      {
        id: 0,
        name: 'Socorro Glover',
      },
      {
        id: 1,
        name: 'Adriana Holt',
      },
      {
        id: 2,
        name: 'Hickman Bentley',
      },
    ],
    greeting: 'Hello, Carla Henson! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '626b31358edef8a51af36a3a',
    index: 1,
    guid: 'bddeaac4-7296-442c-a802-76ae96f8a5e3',
    isActive: true,
    price_formated: '$2,220.52',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'blue',
    name: 'Allie Bradshaw',
    gender: 'female',
    company: 'ORBIN',
    email: 'alliebradshaw@orbin.com',
    phone: '+1 (856) 549-2763',
    address: '851 Montieth Street, Downsville, Washington, 9500',
    about:
      'Exercitation exercitation incididunt tempor aliqua eu. Nulla voluptate ea anim enim amet quis cupidatat. Occaecat nisi labore veniam sit.\r\n',
    registered: '2020-09-17T03:18:33 +03:00',
    latitude: 18.678318,
    longitude: -112.946043,
    tags: ['quis', 'sint', 'irure', 'labore', 'sit', 'magna', 'eiusmod'],
    friends: [
      {
        id: 0,
        name: 'Rosa Byers',
      },
      {
        id: 1,
        name: 'Thornton Harrington',
      },
      {
        id: 2,
        name: 'Mullins Salas',
      },
    ],
    greeting: 'Hello, Allie Bradshaw! You have 5 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '626b313533c97aba785072c1',
    index: 2,
    guid: '55229cee-f2bf-4230-88c6-04742ff7303d',
    isActive: false,
    price_formated: '$3,526.56',
    picture: 'http://placehold.it/32x32',
    age: 22,
    eyeColor: 'blue',
    name: 'Oconnor Mendoza',
    gender: 'male',
    company: 'FLUM',
    email: 'oconnormendoza@flum.com',
    phone: '+1 (812) 550-2038',
    address: '385 Fleet Street, Tedrow, Indiana, 2416',
    about:
      'Non quis irure incididunt reprehenderit nostrud. Aliqua eu laboris deserunt ut. Nulla aute sunt mollit reprehenderit esse eu eu voluptate aute cupidatat ipsum. Fugiat proident consectetur laboris id nisi sint ipsum mollit. Irure enim voluptate occaecat qui aute consequat. Duis veniam cillum ad adipisicing velit in deserunt ut veniam magna duis in. Culpa mollit eiusmod commodo ad elit.\r\n',
    registered: '2016-02-16T05:10:32 +02:00',
    latitude: 9.971178,
    longitude: 160.661112,
    tags: [
      'exercitation',
      'magna',
      'magna',
      'ut',
      'dolor',
      'consectetur',
      'irure',
    ],
    friends: [
      {
        id: 0,
        name: 'Dale Collins',
      },
      {
        id: 1,
        name: 'Hester Mason',
      },
      {
        id: 2,
        name: 'Bauer Kaufman',
      },
    ],
    greeting: 'Hello, Oconnor Mendoza! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '626b313542c0a4f281af1756',
    index: 3,
    guid: '0f026438-7416-4245-95b0-1261486a96ec',
    isActive: true,
    price_formated: '$2,586.25',
    picture: 'http://placehold.it/32x32',
    age: 24,
    eyeColor: 'green',
    name: 'Justine Reese',
    gender: 'female',
    company: 'VORTEXACO',
    email: 'justinereese@vortexaco.com',
    phone: '+1 (868) 555-2908',
    address: '563 Banker Street, Wadsworth, West Virginia, 3164',
    about:
      'Nostrud cillum in qui tempor aliquip occaecat nisi fugiat veniam Lorem non. Non laboris sit aliqua minim. Ad voluptate tempor qui laborum duis magna. Incididunt ut voluptate est cupidatat aute occaecat tempor consequat officia exercitation dolor exercitation cupidatat. Ex quis dolor cillum occaecat voluptate ea nostrud mollit est sint sit.\r\n',
    registered: '2017-08-13T12:24:13 +03:00',
    latitude: -11.900493,
    longitude: -119.678186,
    tags: [
      'pariatur',
      'magna',
      'nostrud',
      'cillum',
      'adipisicing',
      'enim',
      'minim',
    ],
    friends: [
      {
        id: 0,
        name: 'Colette Higgins',
      },
      {
        id: 1,
        name: 'Sadie Farrell',
      },
      {
        id: 2,
        name: 'Jordan Walter',
      },
    ],
    greeting: 'Hello, Justine Reese! You have 3 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '626b31352347bbb3b684a485',
    index: 4,
    guid: '1763e2f8-dc3e-4b9b-8a9b-d04399102ee7',
    isActive: false,
    price_formated: '$1,454.56',
    picture: 'http://placehold.it/32x32',
    age: 34,
    eyeColor: 'blue',
    name: 'Hess Horn',
    gender: 'male',
    company: 'GENMY',
    email: 'hesshorn@genmy.com',
    phone: '+1 (899) 512-3763',
    address: '606 Sedgwick Place, Brownsville, Puerto Rico, 4846',
    about:
      'Magna dolor et exercitation qui. Sint sint duis tempor esse cillum elit esse esse culpa aliquip minim consequat. Excepteur dolor exercitation elit elit dolore do elit mollit. Veniam irure ad non cupidatat officia dolore dolor magna. Ex sunt aute excepteur amet pariatur sit officia in.\r\n',
    registered: '2018-05-25T08:25:22 +03:00',
    latitude: -8.09007,
    longitude: -28.475636,
    tags: ['quis', 'aute', 'laborum', 'laboris', 'et', 'ipsum', 'cillum'],
    friends: [
      {
        id: 0,
        name: 'Ochoa Carver',
      },
      {
        id: 1,
        name: 'Deloris Padilla',
      },
      {
        id: 2,
        name: 'Hamilton Rasmussen',
      },
    ],
    greeting: 'Hello, Hess Horn! You have 10 unread messages.',
    favoriteFruit: 'strawberry',
  },
];
